#!/usr/bin/env node
// Builds src/generated/data.js from the repository (api/, the legacy catalog and the skill's Markdown) so the
// Worker serves exactly what is committed. Run automatically by wrangler (build.command) and by `npm test`.
// Generated output is gitignored; never edit it by hand.
import { execSync } from "node:child_process";
import { mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..", "..");
const OUT = join(HERE, "..", "src", "generated");

// Markdown the MCP serves (same scope as tools/search.py plus the full references tree).
const DOC_ROOTS = ["SKILL.md", "README.md", "tracks", "handbook", "recipes", "references", "evals/README.md"];

function tsv(name) {
	const lines = readFileSync(join(ROOT, "api", name), "utf8").split("\n").filter((l) => l.length > 0);
	const header = lines[0].split("\t");
	return lines.slice(1).map((line) => {
		const cells = line.split("\t");
		const row = {};
		header.forEach((h, i) => (row[h] = cells[i] ?? ""));
		return row;
	});
}

function walk(path) {
	const abs = join(ROOT, path);
	let st;
	try {
		st = statSync(abs);
	} catch {
		return [];
	}
	if (st.isFile()) return path.endsWith(".md") ? [path] : [];
	return readdirSync(abs)
		.sort()
		.flatMap((name) => walk(join(path, name)));
}

function gitCommit() {
	for (const key of ["WORKERS_CI_COMMIT_SHA", "GITHUB_SHA"]) {
		if (process.env[key]) return process.env[key];
	}
	try {
		return execSync("git rev-parse HEAD", { cwd: ROOT, stdio: ["ignore", "pipe", "ignore"] }).toString().trim();
	} catch {
		return "unknown";
	}
}

const classes = {};
for (const r of tsv("classes.tsv")) classes[r.class] = [r.superclass, r.tags, r.summary];

const members = {};
for (const r of tsv("members.tsv")) {
	(members[r.class] ??= {})[r.member] = [r.kind, r.type_or_signature, r.read, r.write, r.thread, r.flags];
}

const enums = {};
for (const r of tsv("enums.tsv")) (enums[r.enum] ??= {})[r.item] = [r.value, r.flags];

const datatypes = {};
for (const r of tsv("datatypes.tsv")) datatypes[r.member] = [r.owner, r.kind, r.signature, r.flags];

const deprecated = {};
// Ordered rows as well: tools/scan_legacy.py builds one generic rule per row, in file order.
const deprecatedRows = [];
for (const r of tsv("deprecated.tsv")) {
	deprecatedRows.push([r.owner, r.member, r.kind, r.preferred, r.message]);
	const key = `${r.owner}.${r.member}`.replace(/\.$/, "");
	deprecated[key] = [r.owner, r.member, r.kind, r.preferred, r.message];
}

const summaries = {};
for (const line of readFileSync(join(ROOT, "api", "summaries.jsonl"), "utf8").split("\n")) {
	if (!line.trim()) continue;
	const d = JSON.parse(line);
	summaries[d.k] = d.s;
}

const apiMeta = JSON.parse(readFileSync(join(ROOT, "api", "META.json"), "utf8"));
const catalogJson = JSON.parse(readFileSync(join(ROOT, "references", "legacy-modernization", "catalog.json"), "utf8"));
const catalog = catalogJson.entries
	.filter((e) => e.detect)
	.map((e) => ({ id: e.id, detect: e.detect, old: e.old, new: e.new, status: e.status, why: e.why ?? "" }));

const docs = [];
for (const root of DOC_ROOTS) {
	for (const path of walk(root)) {
		docs.push({ path: relative(ROOT, join(ROOT, path)).split("\\").join("/"), text: readFileSync(join(ROOT, path), "utf8") });
	}
}

const version = readFileSync(join(ROOT, "VERSION"), "utf8").trim();
const meta = {
	skillVersion: version,
	commit: gitCommit(),
	builtAt: new Date().toISOString(),
	apiClientVersion: apiMeta.generated_from.api_dump.client_version,
	docsCommit: apiMeta.generated_from.engine_yaml.sha,
	counts: { ...apiMeta.counts, catalogRules: catalog.length, docs: docs.length },
};

mkdirSync(OUT, { recursive: true });
const body = [
	"// GENERATED by mcp/scripts/build-data.mjs from the repository. Do not edit.",
	`export const meta = ${JSON.stringify(meta)};`,
	`export const api = ${JSON.stringify({ classes, members, enums, datatypes, deprecated, deprecatedRows, summaries })};`,
	`export const catalog = ${JSON.stringify(catalog)};`,
	`export const docs = ${JSON.stringify(docs)};`,
	"",
].join("\n");
writeFileSync(join(OUT, "data.js"), body);
writeFileSync(
	join(OUT, "data.d.ts"),
	[
		"// GENERATED by mcp/scripts/build-data.mjs. Do not edit.",
		"import type { ApiData, CatalogRule, Doc, Meta } from \"../types\";",
		"export declare const meta: Meta;",
		"export declare const api: ApiData;",
		"export declare const catalog: CatalogRule[];",
		"export declare const docs: Doc[];",
		"",
	].join("\n"),
);
console.log(
	`build-data: ${Object.keys(classes).length} classes, ${catalog.length} catalog rules, ${docs.length} docs, ` +
		`${(body.length / 1024 / 1024).toFixed(2)} MB → src/generated/data.js (skill ${version}, ${meta.commit.slice(0, 12)})`,
);
