#!/usr/bin/env python3
"""Verify legacy guidance, API/doc references, every detector fixture and top-150 coverage.

Write deterministic coverage.json, RANKING.md and fixtures.luau; --check rejects stale artifacts.
--release-gate additionally rejects provisional empirical ranking evidence. Static coverage is not
proof of popular usage, measured model failure, or Studio correctness.
"""
from __future__ import annotations
import argparse
import json
import re
import sys
from pathlib import Path
import api
import check_sources
import check_links
import rank_legacy
import render_legacy

ROOT = Path(__file__).resolve().parents[1]
DIR = ROOT / 'references' / 'legacy-modernization'


def row_fixture(row: dict) -> str:
    name = row['api']
    if row['kind'] == 'class':
        return f'local old = Instance.new("{name}")'
    if row['kind'] == 'global':
        return f'local old = {name}()'
    if row['kind'] == 'EnumItem':
        return f'local old = {name}'
    if row['kind'] in ('datatype', 'library'):
        # Only semantic object names are substituted; this is a regex fixture, not runnable code.
        if row['kind'] == 'datatype':
            member = name.rsplit('.', 1)[1]
            return f'params:{member}(value)' if member == 'AddToFilter' else f'params.{member} = value'
        return f'local old = {name}(value)'
    member = row['member']
    if row['kind'] == 'Function':
        return f'{row["owner"]}:{member}(value)'
    if row['kind'] == 'Event':
        return f'{row["owner"]}.{member}:Connect(callback)'
    return f'{row["owner"]}.{member} = value'


def validate(data: dict, ranking: dict, require_docs: bool = True) -> tuple[list[str], dict]:
    errors = render_legacy.validate(data)
    rows = {r['api']: r for r in ranking['rows']}
    coverage: dict[str, list[str]] = {}
    refs = set()
    for entry in data['entries']:
        rid = entry['id']
        refs.update(entry.get('verify', []))
        regex = re.compile(entry['detect']) if entry.get('detect') else None
        for name in entry.get('covers', []):
            if name not in rows:
                errors.append(f'{rid}: covered API is not in the pinned deprecated list: {name}')
                continue
            if 'api:' + name not in entry.get('verify', []):
                errors.append(f'{rid}: covered API lacks a verification reference: {name}')
            if regex is not None and not regex.search(row_fixture(rows[name])):
                errors.append(f'{rid}: detector misses covered API fixture {name}: {row_fixture(rows[name])}')
            coverage.setdefault(name, []).append(rid)
    for ref in sorted(refs):
        kind, path = ref.split(':', 1)
        if kind == 'api' or require_docs:
            if not check_sources.resolve(kind, path)[0]:
                errors.append(f'Unresolved pinned source: {ref}')
    top = ranking['rows'][:data['ranking']['top_n']]
    missing = [r['api'] for r in top if r['api'] not in coverage]
    if missing:
        errors.append('Uncovered top-ranked APIs: ' + ', '.join(missing))
    report = {
        'schema': 1, 'generated_by': 'tools/check_legacy.py', 'evidence': 'STATIC VERIFIED; detectors are Python-executed; NOT RUN in Studio',
        'catalog_entries': len(data['entries']), 'entries_with_detecting_fixtures': sum(bool(e.get('fixture')) for e in data['entries']),
        'deprecated_rows': len(rows), 'explicitly_covered_rows': len(coverage), 'top_n': len(top),
        'top_n_covered': len(top) - len(missing), 'missing_top_n': missing,
        'api_references': sum(r.startswith('api:') for r in refs),
        'pinned_document_references': sum(not r.startswith('api:') for r in refs),
        'ranking_evidence_status': ranking['evidence_status'],
        'public_code_frequency': ranking['public_code_frequency'],
        'measured_model_outputs': ranking['measured_model_outputs'],
        'official_tutorial_sample': ranking['official_tutorial_sample'],
        'empirical_ranking_release_gate': 'BLOCKED: no representative public/historical tutorial sample or measured model outputs',
        'coverage': dict(sorted(coverage.items())),
    }
    return errors, report


def ranking_markdown(ranking: dict, coverage: dict) -> str:
    measured = ranking['official_tutorial_sample'].get('measurement', {})
    lines = ['# Legacy API priority ranking', '',
             'Generated by `python tools/check_legacy.py`; raw 704-row evidence is in [ranking.json](ranking.json).', '',
             '**Provisional editorial ranking.** These are local eval prompt/fixture identifier mentions and declared risk weights. '
             'They are not representative public/historical tutorial frequencies or measured generated-model failure rates. Those corpora were not sampled.', '',
             'Score: `20 × min(eval-case mentions, 5) + 10 × risk weight + 2 × pinned deprecation message − 40 × restricted/undocumented`. '
             'Ties sort by API name. See [policy](ranking-policy.json). Shared member names require an explicit owner; '
             'other member matches remain lexical signals, not inferred receiver types.', '',
             'Input fingerprints and matching case IDs are preserved in ranking.json. Changing eval prompts can change priority; '
             'rerun ranking and review top-150 coverage together.', '',
             f"A bounded [official tutorial-code sample](tutorial-sample.json) measures {measured.get('code_blocks', 0):,} actual Lua/Luau code blocks in {measured.get('files_with_code', 0)} pinned creator-docs files. "
             'Comments/prose/ordinary strings are excluded. This current official corpus is not representative historical/public popularity; '
             'its lexical candidate counts are reported separately and do not change the risk-first score.', '',
             '| Rank | API | Score | Eval cases | Official code blocks | Curated guidance |', '|---|---|---:|---:|---:|---|']
    entries = {e['id']: e for e in json.loads((DIR / 'catalog.json').read_text(encoding='utf-8'))['entries']}
    for row in ranking['rows'][:150]:
        links_list = []
        for rid in coverage.get(row['api'], []):
            entry = entries[rid]
            heading = f"`{rid}` — {entry['status']}" + (f" (seen {entry['era']})" if entry.get('era') else '')
            links_list.append(f'[{rid}](CATALOG.md#{check_links.slug(heading)})')
        links = ', '.join(links_list)
        lines.append(f"| {row['rank']} | `{row['api']}` | {row['score']} | {row['eval_case_count']} | {row['official_tutorial_code_blocks']} | {links} |")
    return '\n'.join(lines) + '\n'


def fixtures_text(data: dict) -> str:
    lines = ['-- LEGACY: generated detecting fixtures; intentionally incorrect/obsolete examples.',
             '-- These are scanner fixtures, not a runnable Studio script or migration code.',
             '-- Edit catalog.json fixture fields, then run tools/check_legacy.py.', '']
    for e in data['entries']:
        lines.extend(['-- rule: ' + e['id'], e['fixture'], ''])
    return '\n'.join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--check', action='store_true')
    ap.add_argument('--release-gate', action='store_true')
    args = ap.parse_args()
    data = json.loads((DIR / 'catalog.json').read_text(encoding='utf-8'))
    ranking = rank_legacy.build()
    errors, report = validate(data, ranking)
    artifacts = {'coverage.json': json.dumps(report, indent=1, ensure_ascii=False) + '\n',
                 'RANKING.md': ranking_markdown(ranking, report['coverage']), 'fixtures.luau': fixtures_text(data)}
    for name, text in artifacts.items():
        path = DIR / name
        if args.check:
            if not path.exists() or path.read_text(encoding='utf-8') != text:
                errors.append(f'{name} stale: run python tools/check_legacy.py')
        elif not errors:
            path.write_text(text, encoding='utf-8')
    for error in errors:
        print('ERROR', error)
    print(f"legacy coverage: {report['catalog_entries']} entries, {report['explicitly_covered_rows']}/{report['deprecated_rows']} API rows, "
          f"{report['top_n_covered']}/{report['top_n']} top-ranked, {len(errors)} error(s)")
    if args.release_gate:
        print(report['empirical_ranking_release_gate'])
        return 1
    return 1 if errors else 0


if __name__ == '__main__':
    raise SystemExit(main())
