#!/usr/bin/env python3
"""Generate references/limits.md from facts.json; --check detects hand edits or stale output.

Run check_facts.py first to validate pinned source evidence. Rendering also checks
schema and expiry, but does not claim source verification when the corpus is absent.
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import sys
from pathlib import Path

from check_facts import FACTS, ROOT, STATUSES, load_json, parse_date, validate


def cell(value) -> str:
    if not isinstance(value, str):
        value = json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(", ", ": "))
    return value.replace("|", "&#124;").replace("\n", " ")


def render(data: dict) -> str:
    lines = [
        "# Engine and service facts and limits", "",
        "<!-- Generated by tools/render_facts.py from references/facts.json. Do not edit this table by hand. -->", "",
        "Dated statements from pinned documentation and API metadata, not a live-platform guarantee. "
        "Units, scopes, approximate values, and default-vs-hard-limit qualifiers matter. "
        "A documented API or setup procedure alone does not establish general availability.", "",
        "Edit [facts.json](facts.json), then run `python tools/check_facts.py` and `python tools/render_facts.py`. "
        "See the [facts maintenance guide](../maintainers/FACTS.md) for schema, evidence, and expiry policy.", "",
        "## Pinned baseline", "",
    ]
    for name, sha in sorted(data["source_pins"].items()):
        lines.append(f"- {name}: `{sha}`")
    lines += ["", "Status: " + "; ".join(f"**{name}** = {text}" for name, text in STATUSES.items()) + ".", ""]
    sections: dict[str, list[dict]] = {}
    for fact in data["facts"]:
        sections.setdefault(fact["section"], []).append(fact)
    for section, facts in sections.items():
        lines += [f"## {section}", "", "| ID / statement | Value | Unit / scope | Status | Source | Checked / expires |",
                  "|---|---|---|---|---|---|"]
        for fact in facts:
            expiry = parse_date(fact["checked_on"]) + dt.timedelta(days=fact["expires_after"])
            statement = f"`{fact['id']}`: {fact['statement']}"
            if fact.get("notes"):
                statement += " " + fact["notes"]
            source = fact["source"]
            source = f"[pinned source]({source})" if source.startswith("https://") else source
            lines.append("| " + " | ".join(cell(v) for v in (statement, fact["value"], fact["unit"],
                         fact["status"], source, f"{fact['checked_on']} / {expiry}")) + " |")
        lines.append("")
    lines += ["## Verification boundary", "",
              "Expiry is a maintenance deadline, not an announced Roblox release or removal date. "
              "Checks fail on the expiry date, missing evidence, unresolved sources, or changed pins. "
              "Passing checks establishes consistency with the cited snapshot; it does not prove Studio, "
              "multi-client, live-server, or production behavior.", ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--as-of", type=parse_date)
    args = parser.parse_args()
    try:
        data = load_json(FACTS)
        errors = validate(data, as_of=args.as_of)
        if errors:
            for error in errors:
                print("ERROR", error)
            return 1
        output = render(data)
        target = ROOT / "references" / "limits.md"
        if args.check:
            if not target.exists() or target.read_text(encoding="utf-8") != output:
                print("limits.md is stale: run python tools/render_facts.py")
                return 1
        else:
            target.write_text(output, encoding="utf-8")
    except (OSError, ValueError, KeyError, TypeError) as error:
        print(f"ERROR {error}", file=sys.stderr)
        return 1
    print(f"facts table: {len(data['facts'])} entries, {'current' if args.check else 'written'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
